# Generated by Django 5.0.6 on 2024-06-03 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_userprofile_delete_tblstudents'),
    ]

    operations = [
        migrations.CreateModel(
            name='TblStudents',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('dateBirth', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
